title: Mint-blog
email: hyb120934@gmail.com
description: 이유와 목적을 찾기 위한 블로그
author: Mintfrog
baseurl: ""
url: "https://mintfrog-1209.github.io"
future: true

# Social Profiles
twitter_username:
github_username: mintfrog-1209
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
